#!/usr/bin/expect -f

set force_conservative 0  
if {$force_conservative} {
        set send_slow {1 .1}
        proc send {ignore arg} {
                sleep .1
                exp_send -s -- $arg
        }
}

set timeout -1
spawn sshpass -p admin ssh admin@$env(HQ_RTR_IP)
match_max 100000
expect -exact "7\[r\[999;999H\[6n"
send -- "\[24;86R"
expect -exact "hq-rtr>"
send -- "en\rwr\rcopy startup-config ftp ftp://ftpuser:password@$env(HQ_SRV_IP_EX)/pub/hq-rtr-config.tar.gz\rexit\r "
expect eof
